type = "webpack"
account_id = "3811365464a8e56b2b27a5590e328e49"
workers_dev = true

[site]
bucket = "./build"
entry-point = "./scripts/workers-site"

[env.staging]
name = "coliving-staging"
vars = { ENVIRONMENT = "staging", GA = "https://general-admission.staging.coliving.co", SITEMAP = "http://staging.coliving.co.s3-website-us-west-1.amazonaws.com" }

[env.release]
name = "coliving-release-candidate"
vars = { ENVIRONMENT = "production", GA = "https://general-admission.coliving.co", SITEMAP = "http://coliving.co.s3-website-us-west-1.amazonaws.com" }

[env.production]
name = "coliving"
vars = { ENVIRONMENT = "production", GA = "https://general-admission.coliving.co", SITEMAP = "http://coliving.co.s3-website-us-west-1.amazonaws.com" }