import { ID, UID, Collectible, DigitalContent, User } from '@coliving/common'

export enum RepeatMode {
  OFF = 'OFF',
  ALL = 'ALL',
  SINGLE = 'SINGLE'
}

export enum Source {
  COLLECTION_DIGITAL_CONTENTS = 'COLLECTION_DIGITAL_CONTENTS',
  DISCOVER_FEED = 'DISCOVER_FEED',
  DISCOVER_TRENDING = 'DISCOVER_TRENDING',
  HISTORY_DIGITAL_CONTENTS = 'HISTORY_DIGITAL_CONTENTS',
  COLLECTIBLE_CONTENT_LIST_DIGITAL_CONTENTS = 'COLLECTIBLE_CONTENT_LIST_DIGITAL_CONTENTS',
  PROFILE_FEED = 'PROFILE_FEED',
  PROFILE_DIGITAL_CONTENTS = 'PROFILE_DIGITAL_CONTENTS',
  SAVED_DIGITAL_CONTENTS = 'SAVED_DIGITAL_CONTENTS',
  SEARCH_DIGITAL_CONTENTS = 'SEARCH_DIGITAL_CONTENTS',
  DIGITAL_CONTENT_DIGITAL_CONTENTS = 'DIGITAL_CONTENT_DIGITAL_CONTENTS',
  RECOMMENDED_DIGITAL_CONTENTS = 'RECOMMENDED_DIGITAL_CONTENTS'
}

export type Queueable = {
  id: ID | string
  uid: UID
  landlordId?: ID
  collectible?: Collectible
  source: Source
}

export type QueueItem = {
  uid: UID | null
  source: Source | null
  digital_content: DigitalContent | null
  user: User | null
}
